### ISSUE TITLE
GeoServer does not show GeoMesa Menu.

### ISSUE THREAD

**Issue by xqx930807** [geomesa/geomesa-geoserver#8]
I have installed GeoMesa 1.3.0 Jars in GeoServer 2.9.1's WEB-INF/lib/ And I can add GeoMesa DataStores. However, why ''GeoMesa" does not appear in the left bar?​
my screenshot:
![image](https://user-images.githubusercontent.com/3132904/28827447-2f53ee56-7700-11e7-91c2-e906077bde0f.png)
vs PPT from http://www.geomesa.org/outreach/ DC Data Wranglers - Scaling Spatial Analytics, Tuesday, October 21, 2014
![image](https://user-images.githubusercontent.com/3132904/28827466-3c096c7a-7700-11e7-92a3-474cbe9e79c4.png)

here is the jars list in /path/to/tomcat7/webapps/geoserver/WEB-INF​/lib
[lib.txt](https://github.com/geomesa/geomesa-geoserver/files/1190705/lib.txt)

**Comment by xqx930807** [comment]
Sorry.I found no place to ask the question and the mailist haven't accept me.
so I have to ask here,

**Comment by elahrvivaz** [comment]
We removed the 'geomesa' specific menu bar quite a while ago, due to licensing issues and general lack of support for the module. Here is our current [documentation](http://www.geomesa.org/documentation/). I would recommend using our latest version, 1.3.2.
thanks,

**Comment by xqx930807** [comment]
OK,got it.Please close the issue.
